#!/usr/bin/env python3
"""Generate bilingual README files from prompts.json.

Single source of truth: ../prompts.json (relative to this script). Runs in
CI on every PR that touches prompts.json or images/, and locally via:

    python scripts/build_readmes.py

No third-party dependencies — standard library only.
"""

from __future__ import annotations

import html
import json
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "prompts.json"

REPO_URL = "https://github.com/ToseaAI/awesome-gpt-image-2-prompts"
TOSEA_PROMPTS_URL = "https://tosea.ai/prompts/gpt-image-2"
TOSEA_HOME_URL = "https://tosea.ai"

# Display order + localized labels for our 7 canonical buckets. `ui` and
# `thumbnail` are included even if empty to keep schema/README shape stable.
CATEGORY_ORDER = [
    "profile",
    "poster",
    "infographic",
    "social",
    "comic",
    "ui",
    "thumbnail",
]

CATEGORY_LABELS = {
    "en": {
        "profile": "Portrait & Photography",
        "poster": "Poster & Editorial",
        "infographic": "Infographic & Information Design",
        "social": "Social Media & Branding",
        "comic": "Comic & Illustration",
        "ui": "UI & Mockup",
        "thumbnail": "Thumbnail & Cover Art",
    },
    "zh": {
        "profile": "人像与摄影",
        "poster": "海报与编辑设计",
        "infographic": "信息图与数据可视化",
        "social": "社媒与品牌",
        "comic": "漫画与插画",
        "ui": "UI 与模型稿",
        "thumbnail": "缩略图与封面",
    },
}


@dataclass(frozen=True)
class Strings:
    """Locale-keyed strings used by the README template."""

    lang_attr: str
    title: str
    tagline: str
    intro: str
    toc_heading: str
    featured_heading: str
    contributing_heading: str
    contributing_body: str
    license_heading: str
    license_body: str
    prompt_label: str
    show_prompt: str
    try_on_tosea: str
    source_tweet: str
    by_author: str
    lang_switch_label: str
    lang_alt_label: str
    lang_alt_href: str
    entries_total_template: str
    category_count_template: str


STRINGS = {
    "en": Strings(
        lang_attr="en",
        title="Awesome GPT Image 2 Prompts",
        tagline="Pixel-perfect text. Commercial-ready composition. Daily new prompts.",
        intro=(
            "A curated, open-source collection of production-grade prompts for "
            "**OpenAI's GPT Image 2**, organized by use case. "
            "**All prompts are gathered from publicly shared posts on X (Twitter) "
            "and credited to their original authors — each author's name links to "
            "the source post.** If you are an author and want an entry corrected "
            "or removed, please [open an issue]"
            f"({REPO_URL}/issues/new?template=add-prompt.yml)."
        ),
        toc_heading="Table of Contents",
        featured_heading="Featured",
        contributing_heading="Contributing",
        contributing_body=(
            "We welcome PRs. **Only edit `prompts.json`** — the READMEs are "
            "auto-generated by `scripts/build_readmes.py` and will be overwritten "
            "on merge. See [CONTRIBUTING.md](CONTRIBUTING.md) for the exact schema."
        ),
        license_heading="License",
        license_body=(
            "This collection is released under [CC BY 4.0](LICENSE). "
            "Individual prompts remain the intellectual property of their original "
            "authors; we only curate, translate, and categorize."
        ),
        prompt_label="Prompt",
        show_prompt="Show full prompt",
        try_on_tosea="View on Tosea",
        source_tweet="Source",
        by_author="by",
        lang_switch_label="English",
        lang_alt_label="中文",
        lang_alt_href="README.zh-CN.md",
        entries_total_template="{n} prompts across {k} categories",
        category_count_template="{n} prompts",
    ),
    "zh": Strings(
        lang_attr="zh-CN",
        title="Awesome GPT Image 2 Prompts · 精选集",
        tagline="像素级文字掌控,商用级画面质感。每日精选 prompt。",
        intro=(
            "为 **OpenAI GPT Image 2** 整理的生产级 prompt 开源合集,按使用场景分类。"
            "**所有 prompt 均采集自 X (Twitter) 公开推文,作者姓名链接到原推以示署名。**"
            "若您是原作者,希望修改或下架某条,请[提交 Issue]"
            f"({REPO_URL}/issues/new?template=add-prompt.yml)告知我们。"
            "\n\n> 注:当前条目标题保留 prompt 原文语言(多为英文),"
            "中文翻译版本正在规划中。"
        ),
        toc_heading="目录",
        featured_heading="本期精选",
        contributing_heading="贡献指南",
        contributing_body=(
            "欢迎 PR。**请只修改 `prompts.json`** —— README 由 "
            "`scripts/build_readmes.py` 自动生成,手动改会在合并时被覆盖。"
            "数据结构参见 [CONTRIBUTING.md](CONTRIBUTING.md)。"
        ),
        license_heading="许可协议",
        license_body=(
            "本合集采用 [CC BY 4.0](LICENSE) 协议。"
            "每条 prompt 的著作权仍归原作者所有,本仓库仅负责整理、翻译与分类。"
        ),
        prompt_label="Prompt",
        show_prompt="展开完整 prompt",
        try_on_tosea="在 Tosea 浏览",
        source_tweet="原推",
        by_author="作者",
        lang_switch_label="中文",
        lang_alt_label="English",
        lang_alt_href="README.md",
        entries_total_template="共 {n} 条 prompt,覆盖 {k} 个分类",
        category_count_template="{n} 条",
    ),
}


def slugify_anchor(s: str) -> str:
    """GitHub-style anchor slug for markdown headings."""
    return "".join(
        c.lower() if c.isalnum() else "-"
        for c in s.strip()
    ).strip("-").replace("--", "-")


def group_by_category(entries: list[dict]) -> dict[str, list[dict]]:
    buckets: dict[str, list[dict]] = {}
    for e in entries:
        buckets.setdefault(e["category"], []).append(e)
    return buckets


def render_badges() -> str:
    """Top-of-README badge row. Renders via shields.io."""
    lines = [
        '<p align="center">',
        '  <a href="LICENSE"><img alt="License: CC BY 4.0" src="https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg"></a>',
        f'  <a href="{TOSEA_PROMPTS_URL}"><img alt="Gallery on Tosea.ai" src="https://img.shields.io/badge/Gallery-Tosea.ai-000000?style=flat"></a>',
        f'  <a href="{REPO_URL}/stargazers"><img alt="GitHub stars" src="https://img.shields.io/github/stars/ToseaAI/awesome-gpt-image-2-prompts?style=flat&color=yellow"></a>',
        f'  <a href="{REPO_URL}/network/members"><img alt="GitHub forks" src="https://img.shields.io/github/forks/ToseaAI/awesome-gpt-image-2-prompts?style=flat&color=blue"></a>',
        '</p>',
    ]
    return "\n".join(lines)


def render_lang_switch(s: Strings) -> str:
    return (
        f'<p align="center">'
        f'<b>{s.lang_switch_label}</b> · '
        f'<a href="{s.lang_alt_href}">{s.lang_alt_label}</a>'
        f'</p>'
    )


def render_hero_mosaic(
    featured: list[dict],
    lang: str,
    max_images: int = 8,
) -> str:
    """Render a centered 4-col mosaic of up to 8 featured images.

    Uses HTML table so GitHub's limited markdown renders it as a grid rather
    than a vertical stack. Alt text uses the localized title so Google Image
    Search has descriptive above-the-fold context.
    """
    picks = featured[:max_images]
    if not picks:
        return ""

    rows = []
    rows.append('<table align="center"><tr>')
    for i, e in enumerate(picks, 1):
        title = e["title"][lang] if isinstance(e["title"], dict) else e["title"]
        alt = html.escape(title, quote=True)
        rows.append(
            f'<td align="center" width="25%">'
            f'<a href="#{e["id"]}"><img src="{e["image"]}" width="220" alt="{alt}"/></a>'
            f'</td>'
        )
        if i % 4 == 0 and i != len(picks):
            rows.append('</tr><tr>')
    rows.append('</tr></table>')
    return "\n".join(rows)


def render_toc(
    s: Strings,
    lang: str,
    buckets: dict[str, list[dict]],
    ordered_cats: list[str],
) -> str:
    labels = CATEGORY_LABELS[lang]
    lines = [f"## {s.toc_heading}", ""]
    for cat in ordered_cats:
        entries = buckets.get(cat, [])
        if not entries:
            continue
        label = labels[cat]
        count_label = s.category_count_template.format(n=len(entries))
        anchor = slugify_anchor(label)
        lines.append(f"- [{label}](#{anchor}) · *{count_label}*")
    lines.append("")
    return "\n".join(lines)


def render_entry(s: Strings, lang: str, e: dict, n: int) -> str:
    title = e["title"][lang] if isinstance(e["title"], dict) else e["title"]
    # HTML-escape for attribute and summary contexts. Titles occasionally
    # contain straight quotes (`"`) and ampersands which would otherwise
    # break the enclosing alt="..." attribute or the h3 on parsers that are
    # stricter than GitHub's.
    title_attr = html.escape(title, quote=True)
    author_name = e["author"]["displayName"]
    x_handle = e["author"].get("xHandle")
    source_url = e.get("sourceUrl")

    # Attribution: displayName is always the visible text (it is the name
    # the author chose to present). Link target picks the most specific URL
    # we have: the source post beats the profile, profile beats nothing.
    link_target = source_url or (
        f"https://x.com/{x_handle}" if x_handle else None
    )
    if link_target:
        author_md = f"[**{author_name}**]({link_target})"
    else:
        author_md = f"**{author_name}**"

    parts = []
    parts.append(f'### {n:02d}. {title}')
    parts.append("")
    parts.append(f'*{s.by_author} {author_md}*')
    parts.append("")
    parts.append(f'<a id="{e["id"]}"></a>')
    parts.append(f'<p align="center"><a href="{e["image"]}"><img src="{e["image"]}" width="640" alt="{title_attr}"/></a></p>')
    parts.append("")
    parts.append('<details>')
    parts.append(f'<summary><b>{s.prompt_label}</b> — {s.show_prompt}</summary>')
    parts.append("")
    # Use <blockquote> rather than a fenced code block so long prompts wrap
    # naturally. Fenced blocks apply `white-space: pre` + `overflow-x: auto`,
    # which on macOS silently hides the horizontal scrollbar — readers see
    # only the first line of a 600-char prompt with no cue the rest exists.
    # Blockquote wraps and retains visual distinction. Trade-off: we lose
    # the GitHub-provided copy button; readers do a triple-click + Cmd+C.
    # All 60 prompts are single-paragraph, so newline preservation is moot.
    parts.append(
        f'<blockquote>{html.escape(e["prompt"].strip())}</blockquote>'
    )
    parts.append("")
    parts.append('</details>')
    parts.append("")

    # Single CTA — the source post is already linked via the author name
    # above, so no redundant link here. Plain "→ " prefix (not an emoji
    # image) matches the intro summary style and avoids GitHub's zero-
    # padding emoji renderer squashing the label into the arrow.
    parts.append(f'**[→ {s.try_on_tosea}]({e["toseaUrl"]})**')
    parts.append("")
    parts.append("---")
    parts.append("")
    return "\n".join(parts)


def render_readme(lang: str, data: dict) -> str:
    s = STRINGS[lang]
    entries = data["entries"]
    buckets = group_by_category(entries)
    labels = CATEGORY_LABELS[lang]

    ordered_cats = [c for c in CATEGORY_ORDER if buckets.get(c)]
    featured = [e for e in entries if e.get("featured")]

    out = []
    out.append(f'<h1 align="center">{s.title}</h1>')
    out.append("")
    out.append(f'<p align="center"><i>{s.tagline}</i></p>')
    out.append("")
    out.append(render_badges())
    out.append("")
    out.append(render_lang_switch(s))
    out.append("")
    out.append(s.intro)
    out.append("")
    out.append(
        f"> {s.entries_total_template.format(n=len(entries), k=len(ordered_cats))}. "
        f"[→ {s.try_on_tosea}]({TOSEA_PROMPTS_URL})"
    )
    out.append("")

    if featured:
        out.append(f"## {s.featured_heading}")
        out.append("")
        out.append(render_hero_mosaic(featured, lang))
        out.append("")

    out.append(render_toc(s, lang, buckets, ordered_cats))

    for cat in ordered_cats:
        entries_in_cat = buckets[cat]
        label = labels[cat]
        out.append(f"## {label}")
        out.append("")
        # Renumber 1..N per category so readers see "this is the Nth of M
        # in this category" rather than gapped global indices (e.g. 03→11).
        # The anchor (e["id"]) is unchanged, so external deep-links stay
        # stable regardless of renumbering.
        for i, e in enumerate(entries_in_cat, 1):
            out.append(render_entry(s, lang, e, i))

    out.append(f"## {s.contributing_heading}")
    out.append("")
    out.append(s.contributing_body)
    out.append("")
    out.append(f"## {s.license_heading}")
    out.append("")
    out.append(s.license_body)
    out.append("")
    model = data["model"]
    edition_line = (
        f"Edition {model['editionNumber']} · {model['releaseDate']} · "
        f"{len(entries)} prompts"
    )
    out.append(
        f'<p align="center"><sub>{edition_line} · '
        f'Curated by <a href="{TOSEA_HOME_URL}">Tosea.ai</a> · '
        f'Auto-generated from <code>prompts.json</code>.</sub></p>'
    )
    out.append("")

    return "\n".join(out)


def main() -> None:
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))

    for lang, filename in (("en", "README.md"), ("zh", "README.zh-CN.md")):
        content = render_readme(lang, data)
        (ROOT / filename).write_text(content, encoding="utf-8")
        print(f"wrote {filename} ({len(content):,} chars, {len(data['entries'])} entries)")


if __name__ == "__main__":
    main()
